# Generated by Django 4.2.6 on 2023-10-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('father', models.CharField(max_length=255)),
                ('father_phone_number', models.BigIntegerField(blank=True, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_phone_number', models.BigIntegerField(blank=True, null=True)),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
                ('gender', models.CharField(max_length=255)),
                ('date_of_birth', models.CharField(max_length=255)),
                ('uan_no', models.BigIntegerField(blank=True, null=True)),
                ('employee_no', models.IntegerField()),
                ('date_of_joining', models.CharField(blank=True, max_length=255, null=True)),
                ('probation_period', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField()),
                ('type', models.IntegerField(blank=True, null=True)),
                ('salary', models.BigIntegerField(blank=True, db_comment='basic_salary or starting-salary of user', null=True)),
                ('current_salary', models.BigIntegerField(db_comment='current_salary of user')),
                ('payble', models.BigIntegerField(blank=True, null=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(max_length=255)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('device_token', models.TextField(blank=True, null=True)),
                ('screenshot_preview', models.IntegerField(db_comment='1=>show,0=>hide')),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
