# Generated by Django 4.2.6 on 2023-10-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authview', '0002_user_delete_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'auth_user', 'verbose_name_plural': 'auth_user'},
        ),
    ]
